# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY server.py pyproject.toml uv.lock README.md ./

# Install dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.8.0 httpx

# Expose default MCP port (not needed for stdio but as a placeholder)
# EXPOSE 8080

# Start the MCP server
ENTRYPOINT ["mcp", "run", "server.py"]
